// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSnDFQdgcXtImYBfS2X_NES6arcogGOFs',
    appId: '1:204318970766:web:c88a54884381b06b230adf',
    messagingSenderId: '204318970766',
    projectId: 'art-of-evolve',
    authDomain: 'art-of-evolve.firebaseapp.com',
    storageBucket: 'art-of-evolve.firebasestorage.app',
    measurementId: 'G-L6MY86KLD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGWTVApbkI4B66rta85HE2krLK7frHB6U',
    appId: '1:204318970766:android:143f9fd25b1b3d62230adf',
    messagingSenderId: '204318970766',
    projectId: 'art-of-evolve',
    storageBucket: 'art-of-evolve.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb2Cnf9F5nwEyaXuszuNYHGhL1rBVxrdE',
    appId: '1:204318970766:ios:e33c91f6a339fc32230adf',
    messagingSenderId: '204318970766',
    projectId: 'art-of-evolve',
    storageBucket: 'art-of-evolve.firebasestorage.app',
    iosBundleId: 'com.example.artOfEvolve',
  );
}
