// Mocks generated by Mockito 5.4.4 from annotations
// in art_of_evolve/test/unit/habits_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:art_of_evolve/src/core/data/repository_interfaces.dart' as _i3;
import 'package:art_of_evolve/src/features/habits/domain/habit.dart' as _i5;
import 'package:art_of_evolve/src/services/notifications/notification_service.dart'
    as _i6;
import 'package:flutter/material.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:riverpod/src/internals.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProviderContainer_0 extends _i1.SmartFake
    implements _i2.ProviderContainer {
  _FakeProviderContainer_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKeepAliveLink_1 extends _i1.SmartFake implements _i2.KeepAliveLink {
  _FakeKeepAliveLink_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProviderSubscription_2<State1> extends _i1.SmartFake
    implements _i2.ProviderSubscription<State1> {
  _FakeProviderSubscription_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IHabitsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIHabitsRepository extends _i1.Mock implements _i3.IHabitsRepository {
  @override
  _i4.Future<List<_i5.Habit>> getHabits() => (super.noSuchMethod(
        Invocation.method(
          #getHabits,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Habit>>.value(<_i5.Habit>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.Habit>>.value(<_i5.Habit>[]),
      ) as _i4.Future<List<_i5.Habit>>);

  @override
  _i4.Future<void> saveHabit(_i5.Habit? habit) => (super.noSuchMethod(
        Invocation.method(
          #saveHabit,
          [habit],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteHabit(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteHabit,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<List<_i5.Habit>> watchHabits() => (super.noSuchMethod(
        Invocation.method(
          #watchHabits,
          [],
        ),
        returnValue: _i4.Stream<List<_i5.Habit>>.empty(),
        returnValueForMissingStub: _i4.Stream<List<_i5.Habit>>.empty(),
      ) as _i4.Stream<List<_i5.Habit>>);
}

/// A class which mocks [INotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockINotificationService extends _i1.Mock
    implements _i6.INotificationService {
  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> requestPermissions() => (super.noSuchMethod(
        Invocation.method(
          #requestPermissions,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> scheduleReminder({
    required int? id,
    required String? title,
    required String? body,
    required DateTime? scheduledDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleReminder,
          [],
          {
            #id: id,
            #title: title,
            #body: body,
            #scheduledDate: scheduledDate,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> scheduleDailyNotification({
    required int? id,
    required String? title,
    required String? body,
    required _i7.TimeOfDay? time,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleDailyNotification,
          [],
          {
            #id: id,
            #title: title,
            #body: body,
            #time: time,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> scheduleOneOffNotification({
    required int? id,
    required String? title,
    required String? body,
    required Duration? delay,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleOneOffNotification,
          [],
          {
            #id: id,
            #title: title,
            #body: body,
            #delay: delay,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cancelNotification(int? id) => (super.noSuchMethod(
        Invocation.method(
          #cancelNotification,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cancelReminder(int? id) => (super.noSuchMethod(
        Invocation.method(
          #cancelReminder,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [Ref].
///
/// See the documentation for Mockito's code generation for more information.
class MockRef<State extends Object?> extends _i1.Mock
    implements _i2.Ref<State> {
  @override
  _i2.ProviderContainer get container => (super.noSuchMethod(
        Invocation.getter(#container),
        returnValue: _FakeProviderContainer_0(
          this,
          Invocation.getter(#container),
        ),
        returnValueForMissingStub: _FakeProviderContainer_0(
          this,
          Invocation.getter(#container),
        ),
      ) as _i2.ProviderContainer);

  @override
  T refresh<T>(_i2.Refreshable<T>? provider) => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [provider],
        ),
        returnValue: _i8.dummyValue<T>(
          this,
          Invocation.method(
            #refresh,
            [provider],
          ),
        ),
        returnValueForMissingStub: _i8.dummyValue<T>(
          this,
          Invocation.method(
            #refresh,
            [provider],
          ),
        ),
      ) as T);

  @override
  void invalidate(_i2.ProviderOrFamily? provider) => super.noSuchMethod(
        Invocation.method(
          #invalidate,
          [provider],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenSelf(
    void Function(
      State?,
      State,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void invalidateSelf() => super.noSuchMethod(
        Invocation.method(
          #invalidateSelf,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onAddListener(void Function()? cb) => super.noSuchMethod(
        Invocation.method(
          #onAddListener,
          [cb],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onRemoveListener(void Function()? cb) => super.noSuchMethod(
        Invocation.method(
          #onRemoveListener,
          [cb],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onResume(void Function()? cb) => super.noSuchMethod(
        Invocation.method(
          #onResume,
          [cb],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onCancel(void Function()? cb) => super.noSuchMethod(
        Invocation.method(
          #onCancel,
          [cb],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDispose(void Function()? cb) => super.noSuchMethod(
        Invocation.method(
          #onDispose,
          [cb],
        ),
        returnValueForMissingStub: null,
      );

  @override
  T read<T>(_i2.ProviderListenable<T>? provider) => (super.noSuchMethod(
        Invocation.method(
          #read,
          [provider],
        ),
        returnValue: _i8.dummyValue<T>(
          this,
          Invocation.method(
            #read,
            [provider],
          ),
        ),
        returnValueForMissingStub: _i8.dummyValue<T>(
          this,
          Invocation.method(
            #read,
            [provider],
          ),
        ),
      ) as T);

  @override
  bool exists(_i2.ProviderBase<Object?>? provider) => (super.noSuchMethod(
        Invocation.method(
          #exists,
          [provider],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  T watch<T>(_i2.ProviderListenable<T>? provider) => (super.noSuchMethod(
        Invocation.method(
          #watch,
          [provider],
        ),
        returnValue: _i8.dummyValue<T>(
          this,
          Invocation.method(
            #watch,
            [provider],
          ),
        ),
        returnValueForMissingStub: _i8.dummyValue<T>(
          this,
          Invocation.method(
            #watch,
            [provider],
          ),
        ),
      ) as T);

  @override
  _i2.KeepAliveLink keepAlive() => (super.noSuchMethod(
        Invocation.method(
          #keepAlive,
          [],
        ),
        returnValue: _FakeKeepAliveLink_1(
          this,
          Invocation.method(
            #keepAlive,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeKeepAliveLink_1(
          this,
          Invocation.method(
            #keepAlive,
            [],
          ),
        ),
      ) as _i2.KeepAliveLink);

  @override
  _i2.ProviderSubscription<T> listen<T>(
    _i2.ProviderListenable<T>? provider,
    void Function(
      T?,
      T,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
    bool? fireImmediately,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listen,
          [
            provider,
            listener,
          ],
          {
            #onError: onError,
            #fireImmediately: fireImmediately,
          },
        ),
        returnValue: _FakeProviderSubscription_2<T>(
          this,
          Invocation.method(
            #listen,
            [
              provider,
              listener,
            ],
            {
              #onError: onError,
              #fireImmediately: fireImmediately,
            },
          ),
        ),
        returnValueForMissingStub: _FakeProviderSubscription_2<T>(
          this,
          Invocation.method(
            #listen,
            [
              provider,
              listener,
            ],
            {
              #onError: onError,
              #fireImmediately: fireImmediately,
            },
          ),
        ),
      ) as _i2.ProviderSubscription<T>);
}
